apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app
spec:
  selector:
    matchLabels:
      app: my-first-app-pod
  template:
    metadata:
      labels:
        app: my-first-app-pod
    spec:
      containers:
      - name: my-first-app-container
        image: skdcr.azurecr.io/firstwebapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
